import { ObjectId } from "mongodb";


export interface User {
    _id?: ObjectId; // Optional, added by MongoDB
    userId: string; // Generated by server using UUID
    username: string;
    solanaWalletAddress: string;
    password: string; // Should be hashed in production
    email: string;
    firstName: string;
    lastName: string;
    age: number;
    birthdate: string;
    country: string;
    mobileNumber: string;
    twitterHandle: string;
    discordId: string;
    telegramId: string;
    credit: number;
    linked_channels?: {
      twitter_user_id?: string; // From Twitter API
      telegram_user_id?: string; // From Telegram API
      discord_user_id?: string; // From Discord API
      web_user_id?: string; // Added for web-based chat
    };
  }

  // New type for temporary user profiles (unregistered users who link channels)
export interface TemporaryUser {
  _id?: ObjectId;
  temporary_user_id: string; // Generated by server using UUID
  linked_channels: {
    twitter_user_id?: string;
    telegram_user_id?: string;
    discord_user_id?: string;
    web_user_id?: string; // Added for web-based chat
  };
  created_at: Date;
  expires_at: Date; // e.g., 7-day expiration
}